version: '3'
services:
  db:
    image: mysql:8.0.39
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./conf:/etc/mysql/conf.d"
      - persistent:/var/lib/mysql
    networks:
      - lamp-docker
  www:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./:/var/www/html"
    ports:
      - 801:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - lamp-docker
  mysql-workbench:
    depends_on:
      - db
    image: lscr.io/linuxserver/mysql-workbench:latest
    links:
      - db
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PMA_HOST = db
      - PMA_PORT = 3306
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - lamp-docker
  composer:
    image: composer
    links:
      - db
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
volumes:
  persistent:
